"use client";
import { useEffect, useState } from "react";

export const defaultAdminSettings = {
  brandName: "",
  logoUrl: "",
  backgroundUrl: "",
  primaryColor: "#171717",
  termsOfUse: "",
  privacyNotice: "",
  privacyContact: "",
  welcomeText: "",
  unifiUrl: "",
  unifiUsername: "",
  unifiPassword: "",
  unifiUsername2: "",
  unifiPassword2: "",
  unifiPassword2Set: false,
  unifiUsername3: "",
  unifiPassword3: "",
  unifiPassword3Set: false,
  unifiUsername4: "",
  unifiPassword4: "",
  unifiPassword4Set: false,
  unifiSite: "default",
  unifiInsecureTls: true,
  unifiApiType: "auto",
  unifiApiKey: "",
  unifiApiKeySet: false,
  guestDurationMin: 480,
  guestDownKbps: 0,
  guestUpKbps: 0,
  // Derived server-side (never stored/saved): true when this admin process
  // serves no guest pages (split deployment) — links into /portal must then
  // target the guest-serving host.
  guestPagesRemote: false,
  portalSuccessUrl: "",
  portalBaseUrl: "",
  portalTargetIp: "",
  guestBaseUrl: "",
  adminBaseUrl: "",
  reverseProxyMode: "none",
  proxyRootDomains: "",
  criticalAddresses: "",
  pciNetworkIds: "",
  adminAllowedCidrs: "",
  acmeEmail: "",
  cfDnsApiToken: "",
  cfDnsApiTokenSet: false,
  cookieSecure: false,
  deviceSshUsername: "",
  deviceSshPassword: "",
  deviceSshPasswordSet: false,
  deviceSshPort: 22,
  liveRefreshSec: 15,
  alertsEnabled: false,
  alertPollSec: 120,
  alertEmail: "",
  alertWebhookUrl: "",
  alertOfflineEnabled: true,
  alertCpuPct: 90,
  alertFailedLoginCount: 5,
  alertFailedLoginWindowMin: 15,
  alertControllerDownEnabled: true,
  alertControllerDownCycles: 3,
  snmpEnabled: false,
  snmpUser: "",
  snmpAuthKey: "",
  snmpAuthKeySet: false,
  snmpPrivKey: "",
  snmpPrivKeySet: false,
  snmpAuthProtocol: "sha",
  snmpPrivProtocol: "aes",
  snmpPort: 161,
  alarmWebhookSecret: "",
  alarmWebhookSecretSet: false,
  sponsorRequired: false,
  sponsorEmails: "",
  sponsorDomains: "",
  sponsorDefaultMin: 1440,
  sponsorDurationOverride: true,
  warningBannerEnabled: false,
  warningBannerText: "",
  reportEnabled: false,
  reportFrequency: "weekly",
  reportEmail: "",
  configWatchEnabled: false,
  syslogEnabled: false,
  syslogHost: "",
  syslogPort: 514,
  alertMemPct: 90,
  alertFirmwareEnabled: false,
  alertSubsystemEnabled: true,
  alertSaturationPct: 0,
  alertPortErrPct: 0,
  alertRogueExtenderEnabled: false,
  alertFirstSeenEnabled: false,
  dupIpEnabled: false,
  dupIpDryRun: true,
  dupIpCheckMacRandom: true,
  dupIpCheckSessions: true,
  dupIpCheckDhcp: true,
  dupIpCheckArping: false,
  dupIpArpingMap: "",
  updateCheckEnabled: false,
  updateCheckToken: "",
  updateCheckTokenSet: false,
  updateCheckChannel: "stable",
  metricsEnabled: false,
  metricSampleSec: 300,
  metricRetentionDays: 14,
  metricPerDevice: true,
  maxDevicesPerPhone: 5,
  guestQuotaMB: 0,
  defaultRetentionMode: "forever",
  defaultRetentionDays: 0,
  auditRetentionDays: 0,
  emailVerifyEnabled: false,
  emailVerifyInitialMin: 60,
  emailVerifyGraceMin: 30,
  expiryNotifyEnabled: false,
  expiryNotifyLeadMin: 60,
  smtpHost: "",
  smtpPort: 587,
  smtpSecurity: "starttls",
  smtpUser: "",
  smtpPassword: "",
  smtpPasswordSet: false,
  smtpFromEmail: "",
  smtpFromName: "",
  emailProvider: "smtp",
  m365TenantId: "",
  m365ClientId: "",
  m365ClientSecret: "",
  m365ClientSecretSet: false,
  m365Sender: "",
  emailVerifySubject: "",
  emailVerifyHeading: "",
  emailVerifyBody: "",
  emailVerifyButton: "",
  // Read-only, written by the retention job; POST ignores them.
  lastRetentionRunAt: null as string | null,
  lastRetentionStats: null as Record<string, unknown> | null,
};

export type AdminSettings = typeof defaultAdminSettings;

export function useAdminSettings() {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [settings, setSettings] = useState<AdminSettings>(defaultAdminSettings);
  // Snapshot of the last loaded/saved state — `dirty` compares against it so
  // pages can warn that a server-side test would use stale (saved) values.
  const [savedSnapshot, setSavedSnapshot] = useState<AdminSettings | null>(null);

  useEffect(() => {
    fetch("/api/admin/settings")
      .then((res) => res.json())
      .then((data) => {
        const loaded: AdminSettings = {
          brandName:          data.brandName          ?? "",
          logoUrl:            data.logoUrl            ?? "",
          backgroundUrl:      data.backgroundUrl      ?? "",
          primaryColor:       data.primaryColor       ?? "#171717",
          termsOfUse:         data.termsOfUse         ?? "",
          privacyNotice:      data.privacyNotice      ?? "",
          privacyContact:     data.privacyContact     ?? "",
          welcomeText:        data.welcomeText        ?? "Welcome",
          unifiUrl:           data.unifiUrl           ?? "",
          unifiUsername:      data.unifiUsername      ?? "",
          unifiPassword:      data.unifiPassword      ?? "",
          unifiUsername2:     data.unifiUsername2     ?? "",
          unifiPassword2:     "",
          unifiPassword2Set:  data.unifiPassword2Set  ?? false,
          unifiUsername3:     data.unifiUsername3     ?? "",
          unifiPassword3:     "",
          unifiPassword3Set:  data.unifiPassword3Set  ?? false,
          unifiUsername4:     data.unifiUsername4     ?? "",
          unifiPassword4:     "",
          unifiPassword4Set:  data.unifiPassword4Set  ?? false,
          unifiSite:          data.unifiSite          ?? "default",
          unifiInsecureTls:   data.unifiInsecureTls   ?? true,
          unifiApiType:       data.unifiApiType       ?? "auto",
          unifiApiKey:        "",
          unifiApiKeySet:     data.unifiApiKeySet     ?? false,
          guestDurationMin:   data.guestDurationMin   ?? 480,
          guestDownKbps:      data.guestDownKbps      ?? 0,
          guestUpKbps:        data.guestUpKbps        ?? 0,
          guestPagesRemote:   data.guestPagesRemote   ?? false,
          portalSuccessUrl:   data.portalSuccessUrl   ?? "",
          portalBaseUrl:      data.portalBaseUrl      ?? "",
          portalTargetIp:     data.portalTargetIp     ?? "",
          guestBaseUrl:       data.guestBaseUrl       ?? "",
          adminBaseUrl:       data.adminBaseUrl       ?? "",
          reverseProxyMode:   data.reverseProxyMode   ?? "none",
          proxyRootDomains:   data.proxyRootDomains   ?? "",
          criticalAddresses:  data.criticalAddresses  ?? "",
          pciNetworkIds:      data.pciNetworkIds      ?? "",
          adminAllowedCidrs:  data.adminAllowedCidrs  ?? "",
          acmeEmail:          data.acmeEmail          ?? "",
          cfDnsApiToken:      "",
          cfDnsApiTokenSet:   data.cfDnsApiTokenSet   ?? false,
          cookieSecure:          data.cookieSecure          ?? false,
          deviceSshUsername:  data.deviceSshUsername  ?? "",
          deviceSshPassword:  "",
          deviceSshPasswordSet: data.deviceSshPasswordSet ?? false,
          deviceSshPort:      data.deviceSshPort      ?? 22,
          liveRefreshSec:        data.liveRefreshSec         ?? 15,
          alertsEnabled:         data.alertsEnabled         ?? false,
          alertPollSec:          data.alertPollSec          ?? 120,
          alertEmail:            data.alertEmail            ?? "",
          alertWebhookUrl:       data.alertWebhookUrl       ?? "",
          alertOfflineEnabled:   data.alertOfflineEnabled   ?? true,
          alertCpuPct:           data.alertCpuPct           ?? 90,
          alertFailedLoginCount: data.alertFailedLoginCount ?? 5,
          alertFailedLoginWindowMin: data.alertFailedLoginWindowMin ?? 15,
          alertControllerDownEnabled: data.alertControllerDownEnabled ?? true,
          alertControllerDownCycles: data.alertControllerDownCycles ?? 3,
          snmpEnabled: data.snmpEnabled ?? false,
          snmpUser: data.snmpUser ?? "",
          snmpAuthKey: "",
          snmpAuthKeySet: data.snmpAuthKeySet ?? false,
          snmpPrivKey: "",
          snmpPrivKeySet: data.snmpPrivKeySet ?? false,
          snmpAuthProtocol: data.snmpAuthProtocol ?? "sha",
          snmpPrivProtocol: data.snmpPrivProtocol ?? "aes",
          snmpPort: data.snmpPort ?? 161,
          alarmWebhookSecret: "",
          alarmWebhookSecretSet: data.alarmWebhookSecretSet ?? false,
          sponsorRequired: data.sponsorRequired ?? false,
          sponsorEmails: data.sponsorEmails ?? "",
          sponsorDomains: data.sponsorDomains ?? "",
          sponsorDefaultMin: data.sponsorDefaultMin ?? 1440,
          sponsorDurationOverride: data.sponsorDurationOverride ?? true,
          warningBannerEnabled: data.warningBannerEnabled ?? false,
          warningBannerText: data.warningBannerText ?? "",
          reportEnabled: data.reportEnabled ?? false,
          reportFrequency: data.reportFrequency ?? "weekly",
          reportEmail: data.reportEmail ?? "",
          configWatchEnabled: data.configWatchEnabled ?? false,
          syslogEnabled: data.syslogEnabled ?? false,
          syslogHost: data.syslogHost ?? "",
          syslogPort: data.syslogPort ?? 514,
          alertMemPct:           data.alertMemPct           ?? 90,
          alertFirmwareEnabled:  data.alertFirmwareEnabled  ?? false,
          alertSubsystemEnabled: data.alertSubsystemEnabled ?? true,
          alertSaturationPct:    data.alertSaturationPct    ?? 0,
          alertPortErrPct:       data.alertPortErrPct       ?? 0,
          alertRogueExtenderEnabled: data.alertRogueExtenderEnabled ?? false,
          alertFirstSeenEnabled: data.alertFirstSeenEnabled ?? false,
          dupIpEnabled:          data.dupIpEnabled          ?? false,
          dupIpDryRun:           data.dupIpDryRun           ?? true,
          dupIpCheckMacRandom:   data.dupIpCheckMacRandom   ?? true,
          dupIpCheckSessions:    data.dupIpCheckSessions    ?? true,
          dupIpCheckDhcp:        data.dupIpCheckDhcp        ?? true,
          dupIpCheckArping:      data.dupIpCheckArping      ?? false,
          dupIpArpingMap:        data.dupIpArpingMap        ?? "",
          updateCheckEnabled:    data.updateCheckEnabled    ?? false,
          updateCheckToken:      "",
          updateCheckTokenSet:   data.updateCheckTokenSet   ?? false,
          updateCheckChannel:    data.updateCheckChannel    ?? "stable",
          metricsEnabled:        data.metricsEnabled        ?? false,
          metricSampleSec:       data.metricSampleSec       ?? 300,
          metricRetentionDays:   data.metricRetentionDays   ?? 14,
          metricPerDevice:       data.metricPerDevice       ?? true,
          maxDevicesPerPhone: data.maxDevicesPerPhone ?? 5,
          guestQuotaMB:       data.guestQuotaMB       ?? 0,
          defaultRetentionMode: data.defaultRetentionMode ?? "forever",
          defaultRetentionDays: data.defaultRetentionDays ?? 0,
          auditRetentionDays:   data.auditRetentionDays   ?? 0,
          emailVerifyEnabled:    data.emailVerifyEnabled    ?? false,
          emailVerifyInitialMin: data.emailVerifyInitialMin ?? 60,
          emailVerifyGraceMin:   data.emailVerifyGraceMin   ?? 30,
          expiryNotifyEnabled:   data.expiryNotifyEnabled   ?? false,
          expiryNotifyLeadMin:   data.expiryNotifyLeadMin   ?? 60,
          smtpHost:              data.smtpHost              ?? "",
          smtpPort:              data.smtpPort              ?? 587,
          smtpSecurity:          data.smtpSecurity          ?? "starttls",
          smtpUser:              data.smtpUser              ?? "",
          smtpPassword:          "",
          smtpPasswordSet:       data.smtpPasswordSet       ?? false,
          smtpFromEmail:         data.smtpFromEmail         ?? "",
          smtpFromName:          data.smtpFromName          ?? "",
          emailProvider:         data.emailProvider         ?? "smtp",
          m365TenantId:          data.m365TenantId          ?? "",
          m365ClientId:          data.m365ClientId          ?? "",
          m365ClientSecret:      "",
          m365ClientSecretSet:   data.m365ClientSecretSet   ?? false,
          m365Sender:            data.m365Sender            ?? "",
          emailVerifySubject:    data.emailVerifySubject    ?? "",
          emailVerifyHeading:    data.emailVerifyHeading    ?? "",
          emailVerifyBody:       data.emailVerifyBody       ?? "",
          emailVerifyButton:     data.emailVerifyButton     ?? "",
          lastRetentionRunAt:   data.lastRetentionRunAt   ?? null,
          lastRetentionStats:   data.lastRetentionStats   ?? null,
        };
        setSettings(loaded);
        setSavedSnapshot(loaded);
        setLoading(false);
      });
  }, []);

  const set = (key: keyof AdminSettings, value: unknown) =>
    setSettings((prev) => ({ ...prev, [key]: value }));

  // `extra` lets a caller persist a just-computed value in the same call —
  // React state set()s haven't landed yet inside the same handler, so
  // "set(...); save()" alone would post the stale object.
  const save = async (extra?: Partial<AdminSettings>): Promise<boolean> => {
    setSaving(true);
    const payload = extra ? { ...settings, ...extra } : settings;
    try {
      const res = await fetch("/api/admin/settings", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      if (res.ok) setSavedSnapshot(payload);
      return res.ok;
    } catch {
      return false;
    } finally {
      setSaving(false);
    }
  };

  const dirty = savedSnapshot !== null && JSON.stringify(settings) !== JSON.stringify(savedSnapshot);

  return { settings, set, save, loading, saving, dirty };
}
